package com.zhqydot.framework.easymodular.compiler;

import com.google.auto.service.AutoService;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.JavaFileObject;

@AutoService(Processor.class)
public class ModuleProcessor extends AbstractProcessor {

    private Filer mFiler;
    private Elements mElements;
    private Types mTypes;

    @Override public synchronized void init(ProcessingEnvironment processingEnvironment) {
        super.init(processingEnvironment);
        mFiler = processingEnvironment.getFiler();
        mElements = processingEnv.getElementUtils();
        mTypes = processingEnv.getTypeUtils();
    }

    @Override
    public boolean process(Set<? extends TypeElement> set, RoundEnvironment roundEnvironment) {
        Set<? extends Element> moduleElementSet = roundEnvironment.getElementsAnnotatedWith(Module.class);
        List<String> modules = new ArrayList<>();
        TypeMirror typeIModular = mElements.getTypeElement("com.zhqydot.framework.easymodular.core.IModule").asType();
        for (Element element : moduleElementSet) {
            if (!mTypes.isSubtype(element.asType(), typeIModular)) {
                throw new RuntimeException("The module class [" + element.asType().toString() + "] annotated by @Modular must be implements the IModular interface." );
            }
            modules.add(((TypeElement) element).getQualifiedName().toString());
        }
        createFile(modules);
        return true;
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.RELEASE_8;
    }

    @Override public Set<String> getSupportedAnnotationTypes() {
        Set<String> annotations = new LinkedHashSet<>();
        annotations.add(Module.class.getCanonicalName());
        return annotations;
    }

    private void createFile(List<String> modules) {
        try {
            JavaFileObject jfo = mFiler.createSourceFile("com.zhqydot.framework.easymodular.core.ModuleLoader", new Element[]{});
            Writer writer = jfo.openWriter();
            writer.write(brewCode(modules));
            writer.flush();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private String brewCode(List<String> modules) {
        StringBuilder builder = new StringBuilder();
        builder.append("package com.zhqydot.framework.easymodular.core;\n\n");

        builder.append("import com.zhqydot.framework.easymodular.core.IModule;\n");
        builder.append("import android.content.Context;\n");

        appendComment(builder);
        builder.append("public class ModuleLoader { \n\n");
        builder.append("\tpublic void load(Context context) throws Exception { \n");
        for (String module : modules) {
            builder.append("\t\t");
            builder.append(String.format("((IModule) Class.forName(\"%s\").newInstance()).init(context);", module));
            builder.append("\n");
        }
        builder.append("\t}\n");
        builder.append("}");
        return builder.toString();
    }

    private void appendComment(StringBuilder builder) {
        builder.append("\n/**\n");
        builder.append(" * This class was generated by EasyModular\n");
        builder.append(" * do not modify it\n");
        builder.append(" * or it will cause EasyRouter run with exception\n");
        builder.append(" */\n\n");
    }

}
